"use client";

import type { ReportMetadata } from "@/lib/printable-reports";
import { EBPLS_REPORT_HEADING } from "@/lib/printable-reports";

interface ReportPageHeaderProps {
  meta: ReportMetadata;
  /** Override back button behavior. Defaults to window.history.back(). */
  onBack?: () => void;
  /** Override print button behavior. Defaults to window.print(). */
  onPrint?: () => void;
  /** If provided, renders an <a> link instead of a button for the back action. */
  backHref?: string;
}

/**
 * Shared printable report header for Super Admin system reports.
 *
 * Renders:
 * - Back + Print control bar (hidden during print)
 * - Republic / Province / Municipality / Office heading
 * - Report title, period covered, generated-by / generated-at metadata
 * - Print-specific global CSS (hides sidebar, header bar, nav; sets A4 page)
 *
 * Usage: place as the first child inside a .report-print-container wrapper.
 */
export function ReportPageHeader({
  meta,
  onBack,
  onPrint,
  backHref,
}: ReportPageHeaderProps) {
  return (
    <>
      {/* ── Control bar (screen only) ─────────────────────────────────── */}
      <div className="no-print mb-6 flex items-center justify-between gap-3">
        {backHref ? (
          <a
            href={backHref}
            className="inline-flex items-center gap-1 rounded-lg border border-slate-300 bg-white px-4 py-2 text-sm font-semibold text-slate-700 hover:bg-slate-50"
          >
            ← Back to Reports
          </a>
        ) : (
          <button
            type="button"
            onClick={onBack ?? (() => window.history.back())}
            className="inline-flex items-center gap-1 rounded-lg border border-slate-300 bg-white px-4 py-2 text-sm font-semibold text-slate-700 hover:bg-slate-50"
          >
            ← Back
          </button>
        )}

        <button
          type="button"
          onClick={onPrint ?? (() => window.print())}
          className="inline-flex items-center gap-2 rounded-lg border border-indigo-500 bg-indigo-600 px-4 py-2 text-sm font-semibold text-white hover:bg-indigo-700"
        >
          Print Report
        </button>
      </div>

      {/* ── Printable heading ─────────────────────────────────────────── */}
      <header className="space-y-1 border-b border-slate-200 pb-6 text-center">
        <p className="text-xs font-semibold uppercase tracking-[0.16em] text-slate-500">
          {EBPLS_REPORT_HEADING.republic}
        </p>
        <p className="text-xs font-semibold uppercase tracking-[0.12em] text-slate-500">
          {EBPLS_REPORT_HEADING.province}
        </p>
        <p className="text-sm font-semibold uppercase tracking-[0.12em] text-slate-700">
          {meta.municipality}
        </p>
        <p className="text-sm font-semibold uppercase tracking-[0.12em] text-slate-700">
          {meta.office}
        </p>
        <h2 className="pt-2 text-xl font-bold uppercase tracking-[0.10em] text-slate-900">
          {meta.title}
        </h2>

        <p className="mt-3 text-sm text-slate-600">
          <span className="font-semibold">Period Covered:</span> {meta.dateRange}
        </p>

        <div className="mt-2 flex flex-wrap items-center justify-center gap-4 text-xs text-slate-500">
          <span>
            <span className="font-semibold">Generated by:</span> {meta.generatedBy}
          </span>
          <span>
            <span className="font-semibold">Generated at:</span> {meta.generatedAt}
          </span>
        </div>
      </header>

      {/* ── Print-specific global CSS ─────────────────────────────────── */}
      <style jsx global>{`
        @page {
          size: A4 portrait;
          margin: 14mm 12mm;
        }

        @media print {
          html,
          body {
            background: #ffffff !important;
          }

          /* hide all chrome: sidebar, top nav bar, control buttons */
          .no-print,
          nav,
          aside,
          .app-header,
          [data-app-chrome],
          [data-navigation],
          [data-sidebar] {
            display: none !important;
          }

          /* reset container padding so the report fills the page */
          .report-print-container {
            max-width: none !important;
            margin: 0 !important;
            padding: 0 !important;
          }

          /* prevent table rows from splitting across pages */
          .report-table-row {
            page-break-inside: avoid;
          }

          /* explicit page break helper class */
          .report-page-break {
            page-break-before: always;
          }
        }
      `}</style>
    </>
  );
}
