"use client";

import type { ReportMetadata } from "@/lib/printable-reports";
import { MunicipalDocumentHeader } from "@/components/ui/municipal-document-header";

interface ReportPageHeaderProps {
  meta: ReportMetadata;
  /** Override back button behavior. Defaults to window.history.back(). */
  onBack?: () => void;
  /** Override print button behavior. Defaults to window.print(). */
  onPrint?: () => void;
  /** If provided, renders an <a> link instead of a button for the back action. */
  backHref?: string;
}

/**
 * Shared printable report header for IT Administrator system reports.
 * Uses the same municipal heading layout as the Business Permit printout.
 */
export function ReportPageHeader({
  meta,
  onBack,
  onPrint,
  backHref,
}: ReportPageHeaderProps) {
  return (
    <>
      <div className="no-print mb-4 flex items-center justify-between gap-3">
        {backHref ? (
          <a
            href={backHref}
            className="inline-flex items-center gap-1 rounded-lg border border-[var(--border-color)] bg-white px-3 py-2 text-sm font-semibold text-[var(--foreground)] hover:bg-[var(--muted-surface)]"
          >
            ← Back to Reports
          </a>
        ) : (
          <button
            type="button"
            onClick={onBack ?? (() => window.history.back())}
            className="inline-flex items-center gap-1 rounded-lg border border-[var(--border-color)] bg-white px-4 py-2 text-sm font-semibold text-[var(--foreground)] hover:bg-[var(--muted-surface)]"
          >
            ← Back
          </button>
        )}

        <button
          type="button"
          onClick={onPrint ?? (() => window.print())}
          className="inline-flex items-center gap-2 rounded-lg border border-black px-3 py-1.5 text-sm font-semibold text-black"
        >
          Print Report
        </button>
      </div>

      <MunicipalDocumentHeader
        heading={{
          municipality: meta.municipality,
          office: meta.office,
          title: meta.title,
        }}
        titleTone="official"
        meta={
          <div className="space-y-1">
            <p>
              <strong>Period Covered:</strong> {meta.dateRange}
            </p>
            <p>
              <strong>Generated by:</strong> {meta.generatedBy}
            </p>
            <p>
              <strong>Generated at:</strong> {meta.generatedAt}
            </p>
          </div>
        }
      />

      <style jsx global>{`
        @page {
          size: A4 portrait;
          margin: 14mm 12mm;
        }

        @media print {
          html,
          body {
            background: #ffffff !important;
          }

          .no-print,
          nav,
          aside,
          .app-header,
          [data-app-chrome],
          [data-navigation],
          [data-sidebar] {
            display: none !important;
          }

          .report-print-container {
            max-width: none !important;
            margin: 0 !important;
            padding: 0 !important;
          }

          .report-table-row {
            page-break-inside: avoid;
          }

          .report-page-break {
            page-break-before: always;
          }
        }
      `}</style>
    </>
  );
}
