"use client";

import type { ReportMetadata } from "@/lib/printable-reports";
import { EBPLS_REPORT_HEADING } from "@/lib/printable-reports";

interface ReportPageHeaderProps {
  meta: ReportMetadata;
  /** Override back button behavior. Defaults to window.history.back(). */
  onBack?: () => void;
  /** Override print button behavior. Defaults to window.print(). */
  onPrint?: () => void;
  /** If provided, renders an <a> link instead of a button for the back action. */
  backHref?: string;
}

/**
 * Shared printable report header for Super Admin system reports.
 *
 * Renders:
 * - Back + Print control bar (hidden during print)
 * - Republic / Province / Municipality / Office heading
 * - Report title, period covered, generated-by / generated-at metadata
 * - Print-specific global CSS (hides sidebar, header bar, nav; sets A4 page)
 *
 * Usage: place as the first child inside a .report-print-container wrapper.
 */
export function ReportPageHeader({
  meta,
  onBack,
  onPrint,
  backHref,
}: ReportPageHeaderProps) {
  return (
    <>
      {/* ── Control bar (screen only) ─────────────────────────────────── */}
      <div className="no-print mb-4 flex items-center justify-between gap-3">
        {backHref ? (
          <a
            href={backHref}
            className="inline-flex items-center gap-1 px-3 py-1 text-sm font-medium text-black"
          >
            ← Back to Reports
          </a>
        ) : (
          <button
            type="button"
            onClick={onBack ?? (() => window.history.back())}
            className="inline-flex items-center gap-1 rounded-lg border border-slate-300 bg-white px-4 py-2 text-sm font-semibold text-slate-700 hover:bg-slate-50"
          >
            ← Back
          </button>
        )}

        <button
          type="button"
          onClick={onPrint ?? (() => window.print())}
          className="inline-flex items-center gap-2 px-3 py-1 text-sm font-medium text-black border"
        >
          Print Report
        </button>
      </div>

      {/* ── Printable heading ─────────────────────────────────────────── */}
      <header className="pb-4 text-center">
        <p className="text-sm font-semibold uppercase">{EBPLS_REPORT_HEADING.republic}</p>
        <p className="text-sm font-semibold uppercase">{EBPLS_REPORT_HEADING.province}</p>
        <p className="text-sm font-semibold uppercase">{meta.municipality}</p>
        <p className="text-sm font-semibold uppercase">{meta.office}</p>
        <h2 className="pt-2 text-lg font-bold uppercase">{meta.title}</h2>

        <p className="mt-2 text-sm">
          <strong>Period Covered:</strong> {meta.dateRange}
        </p>

        <div className="mt-1 text-xs">
          <div>
            <strong>Generated by:</strong> {meta.generatedBy}
          </div>
          <div>
            <strong>Generated at:</strong> {meta.generatedAt}
          </div>
        </div>
      </header>

      {/* ── Print-specific global CSS ─────────────────────────────────── */}
      <style jsx global>{`
        @page {
          size: A4 portrait;
          margin: 14mm 12mm;
        }

        @media print {
          html,
          body {
            background: #ffffff !important;
          }

          /* hide all chrome: sidebar, top nav bar, control buttons */
          .no-print,
          nav,
          aside,
          .app-header,
          [data-app-chrome],
          [data-navigation],
          [data-sidebar] {
            display: none !important;
          }

          /* reset container padding so the report fills the page */
          .report-print-container {
            max-width: none !important;
            margin: 0 !important;
            padding: 0 !important;
          }

          /* prevent table rows from splitting across pages */
          .report-table-row {
            page-break-inside: avoid;
          }

          /* explicit page break helper class */
          .report-page-break {
            page-break-before: always;
          }
        }
      `}</style>
    </>
  );
}
