"use client";

import Image from "next/image";
import type { JitNoPermitNoticePrintData } from "@/lib/jit-no-permit-ticket";

interface NoPermitNoticeTemplateProps {
  notice: JitNoPermitNoticePrintData;
}

function NoticeField({ label, value }: { label: string; value: string }) {
  return (
    <div className="border-b border-slate-300 py-3">
      <p className="text-xs font-semibold uppercase tracking-wide text-slate-600">{label}</p>
      <p className="mt-1 text-sm font-medium text-black whitespace-pre-wrap">{value}</p>
    </div>
  );
}

export function NoPermitNoticeTemplate({ notice }: NoPermitNoticeTemplateProps) {
  return (
    <section className="mx-auto w-full max-w-[760px] bg-white px-3 py-4 text-black sm:px-4 print:max-w-none print:px-0 print:py-0">
      <div className="no-print mb-3 flex items-center justify-between gap-3">
        <p className="text-sm text-slate-600">
          No-permit notice print preview. Use the print button below to print or save as PDF from your browser.
        </p>
        <button
          type="button"
          onClick={() => window.print()}
          className="rounded border border-black px-3 py-1.5 text-sm font-semibold text-black"
        >
          Print Notice
        </button>
      </div>

      <article className="relative overflow-hidden rounded-2xl border-2 border-red-700 bg-white px-6 py-6 text-black print:rounded-none print:border-2">
        <header className="border-b border-red-200 pb-4 text-center">
          <div className="mx-auto mb-3 flex h-16 w-16 items-center justify-center">
            <Image src="/images/logo.png" alt="Municipality seal" width={64} height={64} className="h-16 w-16 object-contain" />
          </div>
          <p className="text-xs font-semibold uppercase tracking-[0.18em] text-red-800">
            Municipality of Enrique B. Magalona
          </p>
          <h1 className="mt-2 text-xl font-bold uppercase text-red-900">{notice.noticeTitle}</h1>
          <p className="mt-2 text-sm font-semibold text-slate-700">Reference No.: {notice.ticketNumber}</p>
        </header>

        <div className="mt-4 space-y-0">
          <NoticeField label="Establishment Name" value={notice.establishmentName} />
          <NoticeField label="Witness" value={notice.witness} />
          <NoticeField label="Business Address / Location" value={notice.locationLabel} />
          <NoticeField label="Date and Time Recorded" value={notice.recordedAtLabel} />
          <NoticeField label="Inspecting Office" value={notice.inspectingOfficeLabel} />
          <NoticeField label="Inspecting Personnel" value={notice.inspectingPersonnelLabel} />
          <NoticeField label="Findings" value={notice.findings} />
          <NoticeField label="Required Action" value={notice.requiredAction} />
          <NoticeField label="Reference / Ticket Number" value={notice.ticketNumber} />
        </div>

        <footer className="mt-6 border-t border-slate-300 pt-4 text-xs text-slate-600">
          <p>
            This notice is generated by the Business Permit Online System for inspection documentation. Present the
            reference number during BPLO follow-up.
          </p>
        </footer>
      </article>

      <style jsx global>{`
        @page {
          size: A4 portrait;
          margin: 12mm;
        }

        @media print {
          html,
          body {
            background: #ffffff !important;
          }

          .no-print,
          nav,
          aside,
          [data-app-chrome],
          [data-navigation],
          [data-sidebar] {
            display: none !important;
          }
        }
      `}</style>
    </section>
  );
}
